# ***Домашняя работа №1***
## Терешин Кирилл Александрович 
### бфбо-03-24

### ***Задание 1***
>Импорт библиотеки NumPy с общепринятым сокращением (import numpy as np).

In [1]:
import numpy as np

### ***Задание 2***
>Примеры создания массивов:
>- из обычных списков;
>- с использованием функций zeros, ones, arange или аналогичных.

In [28]:
mas = np.array([1,2,3]) # создание массива из обычного списка
print(mas)
print("=" * 20)

nul_mas = np.zeros((3,3)) # создание массива с использованием zeros, размером 3 на 3
print(nul_mas)
print("=" * 20)

ed_mas = np.ones((2,3,4)) # создание массива с использованием ones, размером 2 на 3 на 4
print(ed_mas)
print("=" * 20)

arange_mas = np.arange(1,10,2) # создание массива с использованием arange, создает массив от 1 до 10 с шагом 2
print(arange_mas)
print("=" * 20)

ed_matr = np.eye(5) # создание массива с использованием eye, создает единичную матрицу размером 5 на 5
print(ed_matr)
print("=" * 20)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[1 3 5 7 9]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### ***Задание 3***
>Демонстрация атрибутов:
вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [36]:
mas = np.array([1,2,3])
print(np.shape(a)) # выводится одномерный массив

print(type(a)) # выводится тип данных

(3,)
<class 'numpy.ndarray'>


### ***Задание 4***
>Примеры индексирования и срезов:
>- получение отдельного элемента;
>- извлечение подмассива с помощью среза.

In [43]:
a = np.arange(10) ** 2 # создадим рандомный массив

print(a[2]) # выведем отдельный элемент

print(a[:5]) # извлекаем подмассив с помощью среза

4
[ 0  1  4  9 16]


### ***Задание 5***
>Примеры векторных операций и базовых статистик:
>- поэлементное сложение или умножение массивов;
>- вычисление средней величины (mean) или другой простой статистики.


In [47]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a*b) # поэлеметное умножение массиов
print(np.mean(a*b)) # средняя величина перемноежнных массивов

[  0  20  60 120]
50.0
